name = "forcha"
version = "0.1.0"
license = "license"
author = "Oscar Theran"
maintainer = "oscar.theran@mi.unc.edu.ar"
copyright = "Copyright 2024, Oscar I. Theran"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"