Best_Linear_Regression – Forcha
Best_Linear_Regression Subroutine
MPL
66 statements
Source File
public subroutine Best_Linear_Regression(scn_nc, scn, scn_z, plus_z, a, b, r2, n_init, c_max_blr)
This subroutine calculates the best regression line for an oil.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: scn_nc
integer input variable set to the total number of single cuts being considered in the oil
integer, intent(in), allocatable :: scn(:)
set of singles cuts being considered in the oil
real(kind=pr), intent(in), allocatable :: scn_z(:)
set of corresponding mole fractions of scn cuts
real(kind=pr), intent(in) :: plus_z
composition of residual fraction from input file
real(kind=pr), intent(out) :: a
output real variable. Slope of the best regression line.
real(kind=pr), intent(out) :: b
output real variable. Intercept of the best regression line.
real(kind=pr), intent(out) :: r2
output real variable. Square correlation coefficient.
integer, intent(out) :: n_init
minimum carbon number obtained from the best linear regression
integer, intent(out) :: c_max_blr
output CN at which plus_z is reached, as the summation of single z(i) from the best linear distribution (blr)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: a_best
real(kind=pr), public :: a_old
real(kind=pr), public :: b_best
real(kind=pr), public :: b_old
integer, public :: i
integer, public :: j
integer, public :: k
integer, public :: k_old
integer, public :: n_best
real(kind=pr), public :: r2_best
real(kind=pr), public :: r2_old
integer, public :: x_aux
real(kind=pr), public, dimension(scn_nc) :: x_blr
real(kind=pr), public, dimension(scn_nc) :: y_blr
real(kind=pr), public :: z_aux
real(kind=pr), public :: z_sum
Call graph
best_linear_regression calls linear_regression
difference_mw_plus calls best_linear_regression
get_c_or_m_plus calls difference_mw_plus