characterize – Forcha
characterize Function
MPL
16 statements
Source File
public function characterize(file, mw_source, method, fix_C) result(characterization)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file
file name
character(len=*), intent(in) :: mw_source
character(len=*), intent(in), optional :: method
plus_mw or global_mw
logical, intent(in), optional :: fix_C
Return Value type(FluidDataOut)
Calls
Variables
Type Visibility Attributes Name Initial
type(FluidData), public :: fluid
Call graph
characterize calls data_from_file, density_funtion, get_c_or_m_plus
data_from_file calls mass_fractions, read_components, read_composition, read_density, read_molecular_weight, read_setup
density_funtion calls calculate_volume_6plus
get_c_or_m_plus calls difference_mw_plus
difference_mw_plus calls best_linear_regression, limitline, line_c60_max, select_method
mass_fractions calls read_composition, read_molecular_weight, read_setup
read_components calls read_setup
read_composition calls read_setup
read_density calls read_setup
read_molecular_weight calls read_setup
best_linear_regression calls linear_regression