data_from_file – Forcha
data_from_file Function
MPL
10 statements
Source File
public function data_from_file(file) result(data)
This funtion allows to obtain experimental data from data imput
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file
file name
Return Value type(FluidData)
Calls
Called by
Call graph
data_from_file calls mass_fractions, read_components, read_composition, read_density, read_molecular_weight, read_setup
mass_fractions calls read_composition, read_molecular_weight, read_setup
read_components calls read_setup
read_composition calls read_setup
read_density calls read_setup
read_molecular_weight calls read_setup
characterize calls data_from_file