difference_mw_plus – Forcha
difference_mw_plus Subroutine
MPL
69 statements
Source File
public subroutine difference_mw_plus(fluid, mw_source, method, start, difference, characterization)
this subroutine …
Arguments
Type Intent Optional Attributes Name
type(FluidData), intent(inout) :: fluid
character(len=*), intent(in) :: mw_source
character(len=*), intent(in), optional :: method
logical :: start
real(kind=pr), intent(out) :: difference
type(FluidDataOut), intent(inout) :: characterization
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: a_best
real(kind=pr), public :: a_old
real(kind=pr), public :: b_best
real(kind=pr), public :: b_old
integer, public, dimension(300) :: carbon_number_plus
real(kind=pr), public :: denom
set to molecular weights calculated by
real(kind=pr), public :: half
integer, public :: i
integer, public :: i_0
integer, public :: j
integer, public :: k
integer, public :: k_old
integer, public :: n_best
real(kind=pr), public :: plus_mw_cal
calculated molecular weight of residual fraction
real(kind=pr), public, dimension(300) :: plus_z_i
real(kind=pr), public, dimension(300) :: product_z_mw_plus_i
real(kind=pr), public :: r2_best
real(kind=pr), public :: r2_old
real(kind=pr), public, dimension(300) :: scn_i
real(kind=pr), public :: sum_def_comp_z_plus
compositions sum from (define component +1) to (plus component)
real(kind=pr), public :: sum_z
integer, public :: x_aux
real(kind=pr), public :: z_aux
real(kind=pr), public :: z_sum
Call graph
difference_mw_plus calls best_linear_regression, limitline, line_c60_max, select_method
best_linear_regression calls linear_regression
get_c_or_m_plus calls difference_mw_plus
characterize calls get_c_or_m_plus