difnewMp – Forcha
difnewMp Subroutine
MPL
88 statements
Source File
public subroutine difnewMp(start, C, Ndef, Ncut, rCN, dif, a, b, rM, rMp, maxC, z, zp, zpi, zMpi, w, rn, zcomp, zdef, rMW, rMdef, Mglobal)
Uses
data
this subroutines for a C value returns the correponding Mp value
Arguments
Type Intent Optional Attributes Name
logical :: start
real(kind=pr) :: C
integer :: Ndef
integer :: Ncut
integer, dimension(imax) :: rCN
real(kind=pr) :: dif
real(kind=pr) :: a
real(kind=pr) :: b
real(kind=pr), dimension(imax) :: rM
real(kind=pr) :: rMp
integer :: maxC
real(kind=pr), dimension(imax) :: z
real(kind=pr) :: zp
real(kind=pr), dimension(300) :: zpi
real(kind=pr), dimension(300) :: zMpi
real(kind=pr), dimension(imax) :: w
real(kind=pr), dimension(imax) :: rn
real(kind=pr), dimension(imax) :: zcomp
real(kind=pr), dimension(maxD) :: zdef
real(kind=pr), dimension(imax) :: rMW
real(kind=pr), dimension(maxD) :: rMdef
real(kind=pr) :: Mglobal
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: C60max
integer, public :: CmaxL
real(kind=pr), public, dimension(imax) :: MWt
real(kind=pr), public, dimension(300) :: ZM_1
real(kind=pr), public :: a60
real(kind=pr), public :: aBE
real(kind=pr), public :: alim
real(kind=pr), public :: aold
real(kind=pr), public :: b60
real(kind=pr), public :: bBE
real(kind=pr), public :: blim
real(kind=pr), public :: half
integer, public :: i
integer, public :: i0
integer, public, parameter :: imax = 48
integer, public, parameter :: maxD = 15
real(kind=pr), public :: r2
real(kind=pr), public :: rMpcalc
real(kind=pr), public :: rntot
real(kind=pr), public :: sumz
integer, public, dimension(imax) :: x
real(kind=pr), public, dimension(imax) :: ylog
real(kind=pr), public, dimension(imax) :: ztotal
Call graph
difnewmp calls bestlinearregression, limitline, linec60max
getnewmpfromc calls difnewmp