get_C_or_m_plus – Forcha
get_C_or_m_plus Subroutine
MPL
62 statements
Source File
public subroutine get_C_or_m_plus(oil, mw_source, method, start, C)
This subroutine…
Arguments
Type Intent Optional Attributes Name
type(FluidData) :: oil
character(len=*), intent(in) :: mw_source
character(len=*), intent(in), optional :: method
logical :: start
real(kind=pr) :: C
C constants which is used in equation
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: C_old
real(kind=pr), public :: aux
integer, public :: c_max
output CN at which plus_z is reached, as the summation of single z(i) from the best linear distribution (blr)
real(kind=pr), public :: difference
real(kind=pr), public :: difference_old
real(kind=pr), public, allocatable :: log_scn_z(:)
logarithm of corresponding mole fractions of scn cuts
real(kind=pr), public :: plus_mw
calculated molecular weight of residual fraction
real(kind=pr), public :: plus_mw_old
real(kind=pr), public :: plus_z
composition of residual fraction from input file
Call graph
get_c_or_m_plus calls difference_mw_plus
difference_mw_plus calls best_linear_regression, limitline, line_c60_max, select_method
best_linear_regression calls linear_regression