GetNewMpfromC – Forcha
GetNewMpfromC Subroutine
MPL
31 statements
Source File
public subroutine GetNewMpfromC(start, C, Ncut, rCN, zM, zMp, Z6p, a, b, rMp, maxC, z, zpi, zMpi, Ndef, zp, w, rn, rMWplus, zcomp, zdef, rMW, rMdef, Mglobal)
this subroutines for a C value returns the correponding new M20+ value
Arguments
Type Intent Optional Attributes Name
logical :: start
real(kind=pr) :: C
integer :: Ncut
integer, dimension(imax) :: rCN
real(kind=pr), dimension(imax) :: zM
real(kind=pr) :: zMp
real(kind=pr) :: Z6p
real(kind=pr) :: a
real(kind=pr) :: b
real(kind=pr) :: rMp
integer :: maxC
real(kind=pr), dimension(imax) :: z
real(kind=pr), dimension(300) :: zpi
real(kind=pr), dimension(300) :: zMpi
integer :: Ndef
real(kind=pr) :: zp
real(kind=pr), dimension(imax) :: w
real(kind=pr), dimension(imax) :: rn
real(kind=pr) :: rMWplus
real(kind=pr), dimension(imax) :: zcomp
real(kind=pr), dimension(maxD) :: zdef
real(kind=pr), dimension(imax) :: rMW
real(kind=pr), dimension(maxD) :: rMdef
real(kind=pr) :: Mglobal
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: aux
real(kind=pr), public :: dif
real(kind=pr), public :: dold
integer, public, parameter :: imax = 48
integer, public, parameter :: maxD = 15
real(kind=pr), public, dimension(imax) :: rM
real(kind=pr), public :: rMpold
Call graph
getnewmpfromc calls difmpfromc, difnewmp
difmpfromc calls bestlinearregression, limitline, linec60max
difnewmp calls bestlinearregression, limitline, linec60max