LimitLine – Forcha
LimitLine Subroutine
MPL
25 statements
Source File
public subroutine LimitLine(Ncut, rCN, Zp, aBE, bBE, half, alim, blim, Cmax)
Arguments
Type Intent Optional Attributes Name
integer :: Ncut
integer, dimension(imax) :: rCN
real(kind=pr) :: Zp
real(kind=pr) :: aBE
real(kind=pr) :: bBE
real(kind=pr) :: half
real(kind=pr) :: alim
real(kind=pr) :: blim
integer :: Cmax
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: crossCN
integer, public, parameter :: imax = 48
integer, public :: xaux
real(kind=pr), public :: zaux
real(kind=pr), public :: zcross
real(kind=pr), public :: zlim
Call graph
difmpfromc calls limitline
difmpfromcfull calls limitline
difnewmp calls limitline
get_c calls difmpfromc, difmpfromcfull
getnewmpfromc calls difmpfromc, difnewmp