LineC60max – Forcha
LineC60max Subroutine
MPL
32 statements
Source File
public subroutine LineC60max(Ncut, Zp, rCN, aBE, bBE, half, a60, b60, C60max)
Arguments
Type Intent Optional Attributes Name
integer :: Ncut
real(kind=pr) :: Zp
integer, dimension(imax) :: rCN
real(kind=pr) :: aBE
real(kind=pr) :: bBE
real(kind=pr) :: half
real(kind=pr) :: a60
real(kind=pr) :: b60
integer :: C60max
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: F
real(kind=pr), public :: Ftol
real(kind=pr), public :: Zp60
real(kind=pr), public :: a_old
real(kind=pr), public :: atol
real(kind=pr), public :: crossCN
real(kind=pr), public :: dFdA
integer, public, parameter :: imax = 48
real(kind=pr), public :: range
integer, public :: xaux
real(kind=pr), public :: zaux
real(kind=pr), public :: zcross
real(kind=pr), public :: zsum
Call graph
difmpfromc calls linec60max
difmpfromcfull calls linec60max
difnewmp calls linec60max
get_c calls difmpfromc, difmpfromcfull
getnewmpfromc calls difmpfromc, difnewmp