read_components – Forcha
read_components Subroutine
MPL
18 statements
Source File
public subroutine read_components(file, def_components, scn, scn_plus)
Reads the component names data from input file
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file
file name
character(len=15), intent(out), allocatable :: def_components(:)
names of defined components
integer, intent(out), allocatable :: scn(:)
names of scn fractions
character(len=15), intent(out) :: scn_plus
name of residual fraction
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: def_comp_nc
number of defined components being considered in the oil
integer, public :: funit
integer, public :: numbers_ps
number of pseudos in which the scn fractions grouped
integer, public :: scn_nc
number of single cuts being considered in the oil
integer, public :: scn_nc_ps
CN from which all SCN fractions will be lumped into the specified number of pseudos
Namelists
Namelist nml_components
Variables
Name Type Default Description
def_components character(len=15) None
names of defined components
scn integer None
names of scn fractions
scn_plus character(len=15) None
name of residual fraction
Call graph
read_components calls read_setup
data_from_file calls read_components
characterize calls data_from_file