read_molecular_weight – Forcha
read_molecular_weight Subroutine
MPL
18 statements
Source File
public subroutine read_molecular_weight(file, def_comp_mw, scn_mw, plus_mw)
Reads the molecular weights of each component from the input file
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file
file name
real(kind=pr), intent(out), allocatable :: def_comp_mw(:)
set of corresponding molecular weights of defined components
real(kind=pr), intent(out), allocatable :: scn_mw(:)
set of corresponding molecular weights of scn cuts
real(kind=pr), intent(out) :: plus_mw
molecular weight of residual fraction
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: def_comp_nc
number of defined components being considered in the oil
integer, public :: funit
integer, public :: numbers_ps
number of pseudos in which the scn fractions grouped
integer, public :: scn_nc
number of single cuts being considered in the oil
integer, public :: scn_nc_ps
CN from which all SCN fractions will be lumped into the specified number of pseudos
Namelists
Namelist nml_molecular_weight
Variables
Name Type Default Description
def_comp_mw real(kind=pr) None
set of corresponding molecular weights of defined components
scn_mw real(kind=pr) None
set of corresponding molecular weights of scn cuts
plus_mw real(kind=pr) None
molecular weight of residual fraction
Call graph
read_molecular_weight calls read_setup
data_from_file calls read_molecular_weight, mass_fractions
mass_fractions calls read_molecular_weight
characterize calls data_from_file