read_setup – Forcha
read_setup Subroutine
MPL
12 statements
Source File
public subroutine read_setup(file, def_comp_nc, scn_nc, scn_nc_ps, numbers_ps)
Reads the setup data from input file
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file
file name
integer, intent(out) :: def_comp_nc
number of defined components being considered in the oil
integer, intent(out) :: scn_nc
number of single cuts being considered in the oil
integer, intent(out) :: scn_nc_ps
CN from which all SCN fractions will be lumped into the specified number of pseudos
integer, intent(out) :: numbers_ps
number of pseudos in which the scn fractions grouped
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: funit
Namelists
Namelist nml_setup
Variables
Name Type Default Description
def_comp_nc integer None
number of defined components being considered in the oil
scn_nc integer None
number of single cuts being considered in the oil
scn_nc_ps integer None
CN from which all SCN fractions will be lumped into the specified number of pseudos
numbers_ps integer None
number of pseudos in which the scn fractions grouped
Call graph
data_from_file calls read_setup, mass_fractions, read_components, read_composition, read_density, read_molecular_weight
mass_fractions calls read_setup, read_composition, read_molecular_weight
read_components calls read_setup
read_composition calls read_setup
read_density calls read_setup
read_molecular_weight calls read_setup
characterize calls data_from_file